export const _onSuccess = action => action + '_SUCCESS';
export const _onFail = action => action + '_FAIL';
export const _onUnMount = action => action + '_UNMOUNT';
export default {
  //Get TokenApp
  GET_TOKEN: 'GET_TOKEN',
  //USER
  SAVE_USER_INFO: 'SAVE_USER_INFO',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  UNMOUNT_USER: 'UNMOUNT_USER',
  USER_DELETE_ACCOUNT: 'USER_DELETE_ACCOUNT',
  USER_REGISTER: 'USER_REGISTER',
  USER_FORGOT_PASSWORD: 'USER_FORGOT_PASSWORD',
  USER_CHANGE_PASSWORD: 'USER_CHANGE_PASSWORD',
  USER_CHECK_PASSWORD: 'USER_CHECK_PASSWORD',
  USER_CONFIG: 'USER_CONFIG',
  USER_GET_INFO: 'USER_GET_INFO',
  USER_UPDATE_INFO: 'USER_UPDATE_INFO',
  USER_GET_ADDRESSBOOK: 'USER_GET_ADDRESSBOOK',
  USER_ADD_ADDESSBOOK: 'USER_ADD_ADDESSBOOK',
  USER_UPDATE_ADDRESSBOOK: 'USER_UPDATE_ADDRESSBOOK',
  USER_DELETE_ADDRESSBOOK: 'USER_DELETE_ADDRESSBOOK',
  LOGIN_SOCIAL: 'LOGIN_SOCIAL',

  //Điểm tích luỹ
  USER_GET_CUMULATIVE_POINTS: 'USER_GET_CUMULATIVE_POINTS',
  USER_GET_VOUCHER_REDEEMED: 'USER_GET_VOUCHER_REDEEMED',
  USER_GET_DETAIL_VOUCHER: 'USER_GET_DETAIL_VOUCHER',
  //PRODUCTS
  GET_PRODUCTS_LIST: 'GET_PRODUCTS_LIST',
  GET_DETAIL_PRODUCT: 'GET_DETAIL_PRODUCT',
  GET_GROUP_CATEGORY_PRODUCT: 'GET_GROUP_CATEGORY_PRODUCT',
  GET_DETAIL_PRODUCT_GROUP: 'GET_DETAIL_PRODUCT_GROUP',
  GET_PRODUCT_FILTERS: 'GET_PRODUCT_FILTERS',
  GET_PRODUCT_FOR_YOU: 'GET_PRODUCT_FOR_YOU',
  GET_PRODUCT_YOU_LIKED: 'GET_PRODUCT_YOU_LIKED',
  GET_PRODUCT_RELATED: 'GET_PRODUCT_RELATED',
  GET_PRODUCTS_YOU_VIEWED: 'GET_PRODUCTS_YOU_VIEWED',
  GET_PRODUCTS_YOU_SAVED: 'GET_PRODUCTS_YOU_SAVED',
  GET_PRODUCTS_TOP_RATE: 'GET_PRODUCTS_TOP_RATE',
  GET_PRODUCTS_BESTSELLER: 'GET_PRODUCTS_BESTSELLER',
  CHECK_FAVORITES: 'CHECK_FAVORITES',
  CHECK_SAVED: 'CHECK_SAVED',
  FAVORITES_PRODUCT: 'FAVORITES_PRODUCT',
  SAVE_PRODUCT: 'SAVE_PRODUCT',
  REMOVE_PRODUCT_VIEWED: 'REMOVE_PRODUCT_VIEWED',

  //NEWS
  GET_NEWS_LIST: 'GET_NEWS_LIST',
  //RECRUITMENT
  GET_RECRUITMENT_LIST: 'GET_RECRUITMENT_LIST',
  //UPLOAD
  UPLOADS: 'UPLOADS',
  //LOCATION
  GET_LOCATION_LIST: 'GET_LOCATION_LIST',
  GET_DETAIL_LOCATION: 'GET_DETAIL_LOCATION',
  //ORDER
  GET_ORDER_OF_YOU: 'GET_ORDER_OF_YOU',
  GET_CART_OF_YOU: 'GET_CART_OF_YOU',
  UPDATE_CART_OF_YOU: 'UPDATE_CART_OF_YOU',
  CACL_ORDER: 'CACL_ORDER',
  CREATE_ORDER: 'CREATE_ORDER',
  EVALUATE_ORDER: 'EVALUATE_ORDER',
  CANCEL_ORDER: 'CANCEL_ORDER',
  GET_METHOD_PAYMENT: 'GET_METHOD_PAYMENT',
  GET_METHOD_SHIPPING: 'GET_METHOD_SHIPPING',
  GET_REASON_CANCELLED: 'GET_REASON_CANCELLED',
  GET_STATUS_ORDER: 'GET_STATUS_ORDER',

  //CATALOUGE
  GET_GROUP_CATALOGUE_LIST: 'GET_GROUP_CATALOGUE_LIST',
  GET_CATALOGUE_LIST: 'GET_CATALOGUE_LIST',
  GET_CATALOGUE_DETAIL: 'GET_CATALOGUE_DETAIL',

  //VIDEO
  GET_VIDEO_LIST: 'GET_VIDEO_LIST',
  //VOUCHER
  GET_VOUCHER_LIST: 'GET_VOUCHER_LIST',
  CHECK_VOUCHER: 'CHECK_VOUCHER',
  GET_VOUCHER_CAN_EXCHANGE_LIST: 'GET_VOUCHER_CAN_EXCHANGE_LIST',
  EXCHANGE_POINT_TO_VOUCHER: 'EXCHANGE_POINT_TO_VOUCHER',
  GET_LIST_VOUCHER_EXCHANGE: 'GET_LIST_COUCHER_EXCHANGE',

  //BANNER
  GET_GROUP_BANNER_LIST: 'GET_GROUP_BANNER_LIST',
  GET_BANNER_GROUP: 'GET_BANNER_GROUP',
  // CONTRACT
  GET_CONTRACT_LIST: 'GET_CONTRACT_LIST',
  // DEBT
  GET_DEBT_LIST: 'GET_DEBT_LIST',
  //POSTS
  GET_LIST_POSTS: 'GET_LIST_POSTS',
  GET_POST_DETAIL: 'GET_POST_DETAIL',
  //NOTIFICATION
  GET_NOTIFICATION_LIST: 'GET_NOTIFICATION_LIST',
  GET_NOTIFICATION_DETAIL: 'GET_NOTIFICATION_LIST',
  // ORTHERS
  GET_LANGUAGE: 'GET_LANGUAGE',
  GET_DATA_EXCEL: 'GET_DATA_EXCEL',
  GET_SETTING_MODULE: 'GET_SETTING_MODULE',
};
