export default {
  HOME_SCREEN: 'HOME_SCREEN',
  PRODUCT_SCREEN: 'PRODUCT_SCREEN',
  NOTIFICATION_SCREEN: 'NOTIFICATION_SCREEN',
  ORDER_SCREEN: 'ORDER_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',

  //ROOT
  AUTH_CONTAINER: 'AUTH_CONTAINER',
  BOTTOM_CONTAINER: 'BOTTOM_CONTAINER',
  COMMON_CONTAINER: 'COMMON_CONTAINER',
  TOP_CONTAINER: 'TOP_CONTAINER',
  //AUTH
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  //BOTTOM
  ALL_ORDER: 'ALL_ORDER',
  WAIT_CONFIRM_ORDER: 'WAIT_CONFIRM_ORDER',
  WAIT_GET_ORDER: 'WAIT_GET_ORDER',
  PROCESSING_ORDER: 'PROCESSING_ORDER',
  COMPLETE_ORDER: 'COMPLETE_ORDER',
  CANCEL_ORDER: 'CANCEL_ORDER',
  EVALUATE_ORDER: 'EVALUATE_ORDER',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  // ACCOUNT_PROFILE_SCREEN: 'ACCOUNT_PROFILE_SCREEN',
  INFO_USER: 'INFO_USER',
  ORDER_DETAIL: 'ORDER_DETAIL',
};
