export default {
  HOME_SCREEN: 'HOME_SCREEN',
  PRODUCT_SCREEN: 'PRODUCT_SCREEN',
  NOTIFICATION_SCREEN: 'NOTIFICATION_SCREEN',
  ORDER_SCREEN: 'ORDER_SCREEN',
  ACCOUNT_SCREEN: 'ACCOUNT_SCREEN',

  //ROOT
  AUTH_CONTAINER: 'AUTH_CONTAINER',
  BOTTOM_CONTAINER: 'BOTTOM_CONTAINER',
  COMMON_CONTAINER: 'COMMON_CONTAINER',

  //AUTH
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  ACCOUNT_PROFILE_SCREEN: 'ACCOUNT_PROFILE_SCREEN',
  INFO_USER: 'INFO_USER',
};
